### ISSUE TITLE
Restrict Admin Command use on members with lower Perm level than user

### ISSUE THREAD

**Issue by lehenbnw** [tbackus127/RathBot#14]
Admin commands should only be allowed to be used on users with a lower permission level than the person who initiates the command. This will prevent users with Moderator level permissions from kicking or banning members in the Admin level.

Options:
 - Can be implemented in the RathBot.java methods
 - Can be implemented as its own RathBot.java (or other class) method
 - Can be implemented in each Admin command's own class.

**Comment by tbackus127** [comment]
Done.
