### ISSUE TITLE
MessageHelper method: getUIDFromToken

### ISSUE THREAD

**Issue by lehenbnw** [tbackus127/RathBot#27]
We seem to use this function a lot, as suggested I'm going to add the method to our MessageHelper to handle this so we don't have to keep copy and pasting it.

**Comment by lehenbnw** [comment]
In fact, we generally use the UID just to create a user object, I'm also going to add a getUserFromToken that will utilize getUIDFromToken. Anything to reduce the number of lines in our code.

**Comment by tbackus127** [comment]
Completed.
